services:
# this is mongodb service configuration for docker-compose.yml file
  mongodb:
    image: mongo:latest
    container_name: elearn_database
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
# backend service
  backend:
    build: ./backend
    container_name: elearn_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    restart: on-failure

  frontend:
    build: .
    container_name: elearn_frontend
    ports:
      - "5500:80"
    depends_on:
      - backend

volumes:
  mongo_data: